spring:
  redis:
    database: 1
    ###host: 127.0.0.1
    host: 106.54.55.188
    port: 6379
    ##password: tansun
    password: root
  datasource:
      username: campus_club
      password: root
      url: jdbc:mysql://106.54.55.188:3306/campus_club
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

